<CustButton@Button>:
    font_size: 32
    color: 0, 0, 0, 1
    size: 50, 50
    background_normal: ''
    background_down: 'bkgrd-down-color.png'
    background_color: .88, .88, .88, 1
    size_hint: .4, .3

<FloatLayout>:
    CustButton:
        text: "Diets"
        pos_hint: {"center_x": .5, "top": 1}
    CustButton:
        text: "Exercise"
        pos_hint: {"center_x": .5, "center_y": .5}
    CustButton:
        text: "Medication"
        pos_hint: {"center_x": .5, "y": 0}