<CustButton@Button>:
    font_size: 32
    color: 0, 0, 0, 1
    background_normal: ''
    background_down: 'button_background.png'
    background_color: .88, .88, .88, 1
    size_hint: .5, .2

<FloatLayout>:
    CustButton:
        text: "Diets"
        pos_hint: {"center_x": .5, "top": .9}
    CustButton:
        text: "Exercise"
        pos_hint: {"center_x": .5, "center_y": .5}
    CustButton:
        text: "Medication"
        pos_hint: {"center_x": .5, "y": .1}